// Copyright (c) 2026 threatvec & talkdedsec. All Rights Reserved.
// This software is proprietary and confidential.

package ai

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// AIMessage represents a single chat message stored in history.
type AIMessage struct {
	ID        int64  `json:"id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	Provider  string `json:"provider"`
	Timestamp string `json:"timestamp"`
}

// ProviderStatus holds connection status for an AI provider.
type ProviderStatus struct {
	Provider  string `json:"provider"`
	Available bool   `json:"available"`
	Model     string `json:"model"`
	Error     string `json:"error,omitempty"`
}

// OllamaModelInfo holds info about an Ollama model.
type OllamaModelInfo struct {
	Name string `json:"name"`
	Size string `json:"size"`
}

// AnalyzeScanResult takes raw scan result JSON and asks AI to provide a risk analysis.
func (m *Manager) AnalyzeScanResult(toolName string, resultJSON string) (string, error) {
	prompt := fmt.Sprintf(`You are VAULTX security analyst. Analyze the following %s scan results and provide:

1. **Risk Assessment**: Overall risk level (Critical/High/Medium/Low)
2. **Key Findings**: Bullet points of the most important findings
3. **Threats Identified**: What specific threats or vulnerabilities exist
4. **Recommended Actions**: Concrete steps the user should take
5. **Summary**: 2-3 sentence executive summary

Scan Results:
%s

Be concise, actionable, and focus on the most critical findings first.`, toolName, resultJSON)

	return m.Query(prompt)
}

// GenerateRiskSummary generates a risk summary from multiple scan data points.
func (m *Manager) GenerateRiskSummary(scans map[string]interface{}) (string, error) {
	data, err := json.MarshalIndent(scans, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to marshal scan data: %w", err)
	}

	prompt := fmt.Sprintf(`You are VAULTX security analyst. Generate a comprehensive risk summary from the following scan results collected over the recent period.

Data:
%s

Provide:
1. **Overall Risk Score**: 0-100 with justification
2. **Critical Issues**: Items needing immediate attention
3. **Trends**: Any patterns or recurring issues
4. **Top Recommendations**: 5 most important actions to take
5. **Executive Summary**: Brief paragraph for non-technical stakeholders

Format your response in clean markdown.`, string(data))

	return m.Query(prompt)
}

// AnswerSecurityQuestion answers a cybersecurity question with optional context.
func (m *Manager) AnswerSecurityQuestion(question string, context string) (string, error) {
	var prompt string
	if context != "" {
		prompt = fmt.Sprintf(`You are VAULTX AI security assistant. Answer the following question using the provided context.

Context:
%s

Question: %s

Provide a clear, accurate, and actionable answer.`, context, question)
	} else {
		prompt = fmt.Sprintf(`You are VAULTX AI security assistant. Answer this cybersecurity question:

%s

Be clear, accurate, and provide actionable guidance when applicable.`, question)
	}

	return m.Query(prompt)
}

// GenerateWeeklyReport generates a comprehensive weekly security report.
func (m *Manager) GenerateWeeklyReport(queryHistory []map[string]string) (string, error) {
	data, err := json.MarshalIndent(queryHistory, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to marshal history: %w", err)
	}

	today := time.Now().Format("January 2, 2006")
	weekAgo := time.Now().AddDate(0, 0, -7).Format("January 2, 2006")

	prompt := fmt.Sprintf(`You are VAULTX security analyst generating a weekly report.

Period: %s — %s

Below are the scan/query results from the past week across multiple security tools:

%s

Generate a professional Weekly Security Report with these sections:

# VAULTX Weekly Security Report
## Period: %s — %s

### Executive Summary
(2-3 sentences overview)

### Activity Overview
- Total scans performed
- Tools used
- Notable targets analyzed

### Critical Findings
(Bulleted list of the most important issues found)

### Risk Assessment
(Overall risk posture: Low/Medium/High/Critical with justification)

### Trends & Patterns
(Any recurring issues or patterns observed)

### Recommendations
(Top 5 actionable recommendations)

### Conclusion
(Brief closing statement)

---
*Generated by VAULTX AI — %s*

Format the response as clean markdown. If the data is limited, note that and provide recommendations based on what's available.`,
		weekAgo, today, string(data), weekAgo, today, today)

	return m.Query(prompt)
}

// GetActiveProvider returns the currently active AI provider name.
func (m *Manager) GetActiveProvider() string {
	settings, err := m.db.GetAllSettings()
	if err != nil {
		if m.ollama.IsAvailable() {
			return string(ProviderOllama)
		}
		return "none"
	}

	preferred := settings["ai_provider"]
	if preferred != "" {
		switch Provider(preferred) {
		case ProviderOpenAI:
			if key, ok := settings["openai_api_key"]; ok && key != "" {
				return string(ProviderOpenAI)
			}
		case ProviderAnthropic:
			if key, ok := settings["anthropic_api_key"]; ok && key != "" {
				return string(ProviderAnthropic)
			}
		case ProviderGemini:
			if key, ok := settings["gemini_api_key"]; ok && key != "" {
				return string(ProviderGemini)
			}
		case ProviderOllama:
			if m.ollama.IsAvailable() {
				return string(ProviderOllama)
			}
		}
	}

	if m.ollama.IsAvailable() {
		return string(ProviderOllama)
	}
	if key, ok := settings["openai_api_key"]; ok && key != "" {
		return string(ProviderOpenAI)
	}
	if key, ok := settings["anthropic_api_key"]; ok && key != "" {
		return string(ProviderAnthropic)
	}
	if key, ok := settings["gemini_api_key"]; ok && key != "" {
		return string(ProviderGemini)
	}
	return "none"
}

// ListOllamaModels returns the available Ollama models from default URL.
func (m *Manager) ListOllamaModels() ([]OllamaModelInfo, error) {
	if !m.ollama.IsAvailable() {
		return nil, fmt.Errorf("Ollama is not running")
	}
	return m.ollama.ListModels()
}

// ListOllamaModelsFromURL returns available Ollama models from the given URL.
func (m *Manager) ListOllamaModelsFromURL(url string) ([]OllamaModelInfo, error) {
	if !m.ollama.TestConnectionURL(url) {
		return nil, fmt.Errorf("Ollama is not reachable at %s", url)
	}
	return m.ollama.ListModelsFromURL(url)
}

// TestOllamaURL checks if Ollama is reachable at the given URL.
func (m *Manager) TestOllamaURL(url string) bool {
	return m.ollama.TestConnectionURL(url)
}

// TestProvider tests a specific AI provider connection.
func (m *Manager) TestProvider(provider, apiKey, model string) (*ProviderStatus, error) {
	status := &ProviderStatus{Provider: provider}

	testPrompt := "Reply with exactly: OK"

	switch Provider(provider) {
	case ProviderOllama:
		if !m.ollama.IsAvailable() {
			status.Available = false
			status.Error = "Ollama is not running on localhost:11434"
			return status, nil
		}
		if model == "" {
			model = "llama3.2"
		}
		_, err := m.ollama.Query(model, testPrompt)
		if err != nil {
			status.Available = false
			status.Error = err.Error()
		} else {
			status.Available = true
			status.Model = model
		}

	case ProviderOpenAI:
		if apiKey == "" {
			status.Available = false
			status.Error = "API key is required"
			return status, nil
		}
		_, err := m.openai.Query(apiKey, testPrompt)
		if err != nil {
			status.Available = false
			status.Error = err.Error()
		} else {
			status.Available = true
			status.Model = "gpt-4o"
		}

	case ProviderAnthropic:
		if apiKey == "" {
			status.Available = false
			status.Error = "API key is required"
			return status, nil
		}
		_, err := m.anthropic.Query(apiKey, testPrompt)
		if err != nil {
			status.Available = false
			status.Error = err.Error()
		} else {
			status.Available = true
			status.Model = "claude-sonnet-4-20250514"
		}

	case ProviderGemini:
		if apiKey == "" {
			status.Available = false
			status.Error = "API key is required"
			return status, nil
		}
		_, err := m.gemini.Query(apiKey, testPrompt)
		if err != nil {
			status.Available = false
			status.Error = err.Error()
		} else {
			status.Available = true
			status.Model = "gemini-pro"
		}

	default:
		return nil, fmt.Errorf("unknown provider: %s", provider)
	}

	return status, nil
}

// ListModels returns available models from the default Ollama instance.
func (o *OllamaClient) ListModels() ([]OllamaModelInfo, error) {
	return o.ListModelsFromURL(ollamaEndpoint)
}

// ListModelsFromURL returns available models from an Ollama instance at the given URL.
func (o *OllamaClient) ListModelsFromURL(url string) ([]OllamaModelInfo, error) {
	if url == "" {
		url = ollamaEndpoint
	}
	resp, err := o.client.Get(url + "/api/tags")
	if err != nil {
		return nil, fmt.Errorf("failed to connect to Ollama: %w", err)
	}
	defer resp.Body.Close()

	var result struct {
		Models []struct {
			Name string `json:"name"`
			Size int64  `json:"size"`
		} `json:"models"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to parse Ollama models: %w", err)
	}

	var models []OllamaModelInfo
	for _, m := range result.Models {
		sizeStr := formatSize(m.Size)
		models = append(models, OllamaModelInfo{
			Name: m.Name,
			Size: sizeStr,
		})
	}
	return models, nil
}

func formatSize(bytes int64) string {
	const (
		mb = 1024 * 1024
		gb = 1024 * 1024 * 1024
	)
	switch {
	case bytes >= gb:
		return fmt.Sprintf("%.1f GB", float64(bytes)/float64(gb))
	case bytes >= mb:
		return fmt.Sprintf("%.0f MB", float64(bytes)/float64(mb))
	default:
		return fmt.Sprintf("%d B", bytes)
	}
}

// SetProvider saves the preferred AI provider and credentials.
func (m *Manager) SetProvider(provider, apiKey, model string) error {
	if err := m.db.SaveSetting("ai_provider", provider); err != nil {
		return err
	}

	provider = strings.TrimSpace(provider)
	switch Provider(provider) {
	case ProviderOpenAI:
		if apiKey != "" {
			return m.db.SaveSetting("openai_api_key", apiKey)
		}
	case ProviderAnthropic:
		if apiKey != "" {
			return m.db.SaveSetting("anthropic_api_key", apiKey)
		}
	case ProviderGemini:
		if apiKey != "" {
			return m.db.SaveSetting("gemini_api_key", apiKey)
		}
	case ProviderOllama:
		if model != "" {
			return m.db.SaveSetting("ollama_model", model)
		}
	}
	return nil
}
