// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScheduledTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddScheduledTask'](arg1, arg2, arg3, arg4);
}

export function AddWatchTarget(arg1, arg2) {
  return window['go']['main']['App']['AddWatchTarget'](arg1, arg2);
}

export function AnalyzeDocument(arg1) {
  return window['go']['main']['App']['AnalyzeDocument'](arg1);
}

export function AnalyzePassword(arg1) {
  return window['go']['main']['App']['AnalyzePassword'](arg1);
}

export function AnalyzePhishing(arg1) {
  return window['go']['main']['App']['AnalyzePhishing'](arg1);
}

export function AnalyzeWithAI(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeWithAI'](arg1, arg2);
}

export function BookmarkLog(arg1, arg2) {
  return window['go']['main']['App']['BookmarkLog'](arg1, arg2);
}

export function CheckEmailBreach(arg1) {
  return window['go']['main']['App']['CheckEmailBreach'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckIPReputation(arg1) {
  return window['go']['main']['App']['CheckIPReputation'](arg1);
}

export function CheckPasswordBreach(arg1) {
  return window['go']['main']['App']['CheckPasswordBreach'](arg1);
}

export function CheckPastes(arg1) {
  return window['go']['main']['App']['CheckPastes'](arg1);
}

export function CompareHashes(arg1, arg2) {
  return window['go']['main']['App']['CompareHashes'](arg1, arg2);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function DecodeQR(arg1) {
  return window['go']['main']['App']['DecodeQR'](arg1);
}

export function DeleteAllQueryLogs() {
  return window['go']['main']['App']['DeleteAllQueryLogs']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteQueryLogs(arg1) {
  return window['go']['main']['App']['DeleteQueryLogs'](arg1);
}

export function EncodeAll(arg1) {
  return window['go']['main']['App']['EncodeAll'](arg1);
}

export function ExportShadowScanPDF(arg1) {
  return window['go']['main']['App']['ExportShadowScanPDF'](arg1);
}

export function ExtractFileMetadata(arg1) {
  return window['go']['main']['App']['ExtractFileMetadata'](arg1);
}

export function ExtractImageEXIF(arg1) {
  return window['go']['main']['App']['ExtractImageEXIF'](arg1);
}

export function FingerprintWeb(arg1) {
  return window['go']['main']['App']['FingerprintWeb'](arg1);
}

export function GenerateDorks(arg1) {
  return window['go']['main']['App']['GenerateDorks'](arg1);
}

export function GenerateIdentityDorks(arg1) {
  return window['go']['main']['App']['GenerateIdentityDorks'](arg1);
}

export function GeneratePasswords(arg1) {
  return window['go']['main']['App']['GeneratePasswords'](arg1);
}

export function GenerateTOTPSecret(arg1, arg2) {
  return window['go']['main']['App']['GenerateTOTPSecret'](arg1, arg2);
}

export function GenerateWeeklyReport() {
  return window['go']['main']['App']['GenerateWeeklyReport']();
}

export function GetAIHistory(arg1) {
  return window['go']['main']['App']['GetAIHistory'](arg1);
}

export function GetAIProvider() {
  return window['go']['main']['App']['GetAIProvider']();
}

export function GetBadges() {
  return window['go']['main']['App']['GetBadges']();
}

export function GetClipboardWatcherEnabled() {
  return window['go']['main']['App']['GetClipboardWatcherEnabled']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetHTTPHeaders(arg1) {
  return window['go']['main']['App']['GetHTTPHeaders'](arg1);
}

export function GetLicense() {
  return window['go']['main']['App']['GetLicense']();
}

export function GetMyIP() {
  return window['go']['main']['App']['GetMyIP']();
}

export function GetOllamaStatus() {
  return window['go']['main']['App']['GetOllamaStatus']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetQueryHistory(arg1, arg2) {
  return window['go']['main']['App']['GetQueryHistory'](arg1, arg2);
}

export function GetQueryLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetQueryLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetRecentActivity(arg1) {
  return window['go']['main']['App']['GetRecentActivity'](arg1);
}

export function GetScheduledTasks() {
  return window['go']['main']['App']['GetScheduledTasks']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTOTPCode(arg1) {
  return window['go']['main']['App']['GetTOTPCode'](arg1);
}

export function GetThreatFeedData() {
  return window['go']['main']['App']['GetThreatFeedData']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWatchTargets() {
  return window['go']['main']['App']['GetWatchTargets']();
}

export function HashFilePath(arg1) {
  return window['go']['main']['App']['HashFilePath'](arg1);
}

export function HashFileVT(arg1) {
  return window['go']['main']['App']['HashFileVT'](arg1);
}

export function HashText(arg1) {
  return window['go']['main']['App']['HashText'](arg1);
}

export function InspectSSL(arg1) {
  return window['go']['main']['App']['InspectSSL'](arg1);
}

export function ListOllamaModels() {
  return window['go']['main']['App']['ListOllamaModels']();
}

export function LookupBGP(arg1) {
  return window['go']['main']['App']['LookupBGP'](arg1);
}

export function LookupDNS(arg1) {
  return window['go']['main']['App']['LookupDNS'](arg1);
}

export function LookupDNSForward(arg1) {
  return window['go']['main']['App']['LookupDNSForward'](arg1);
}

export function LookupDNSReverse(arg1) {
  return window['go']['main']['App']['LookupDNSReverse'](arg1);
}

export function LookupGeoMap(arg1) {
  return window['go']['main']['App']['LookupGeoMap'](arg1);
}

export function LookupHashVT(arg1) {
  return window['go']['main']['App']['LookupHashVT'](arg1);
}

export function LookupIPIntel(arg1) {
  return window['go']['main']['App']['LookupIPIntel'](arg1);
}

export function LookupPhone(arg1) {
  return window['go']['main']['App']['LookupPhone'](arg1);
}

export function LookupWHOIS(arg1) {
  return window['go']['main']['App']['LookupWHOIS'](arg1);
}

export function LookupWayback(arg1) {
  return window['go']['main']['App']['LookupWayback'](arg1);
}

export function MonitorPastes(arg1) {
  return window['go']['main']['App']['MonitorPastes'](arg1);
}

export function OpenAnyFileDialog(arg1) {
  return window['go']['main']['App']['OpenAnyFileDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenImageDialog(arg1) {
  return window['go']['main']['App']['OpenImageDialog'](arg1);
}

export function ParseEmailHeader(arg1) {
  return window['go']['main']['App']['ParseEmailHeader'](arg1);
}

export function PingHost(arg1, arg2) {
  return window['go']['main']['App']['PingHost'](arg1, arg2);
}

export function ProcessEncoder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessEncoder'](arg1, arg2, arg3, arg4);
}

export function QueryAI(arg1) {
  return window['go']['main']['App']['QueryAI'](arg1);
}

export function ReadFileAsBase64(arg1) {
  return window['go']['main']['App']['ReadFileAsBase64'](arg1);
}

export function RemoveScheduledTask(arg1) {
  return window['go']['main']['App']['RemoveScheduledTask'](arg1);
}

export function RemoveWatchTarget(arg1) {
  return window['go']['main']['App']['RemoveWatchTarget'](arg1);
}

export function RunOSINTDashboard(arg1) {
  return window['go']['main']['App']['RunOSINTDashboard'](arg1);
}

export function RunSelfScan() {
  return window['go']['main']['App']['RunSelfScan']();
}

export function RunShadowScan(arg1) {
  return window['go']['main']['App']['RunShadowScan'](arg1);
}

export function SaveAIMessage(arg1, arg2) {
  return window['go']['main']['App']['SaveAIMessage'](arg1, arg2);
}

export function SaveQueryLog(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveQueryLog'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function ScanPorts(arg1, arg2) {
  return window['go']['main']['App']['ScanPorts'](arg1, arg2);
}

export function ScanURL(arg1) {
  return window['go']['main']['App']['ScanURL'](arg1);
}

export function SearchCVE(arg1) {
  return window['go']['main']['App']['SearchCVE'](arg1);
}

export function SearchUsername(arg1) {
  return window['go']['main']['App']['SearchUsername'](arg1);
}

export function SetAIProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAIProvider'](arg1, arg2, arg3);
}

export function SetClipboardWatcherEnabled(arg1) {
  return window['go']['main']['App']['SetClipboardWatcherEnabled'](arg1);
}

export function TestAIProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestAIProvider'](arg1, arg2, arg3);
}

export function TestEmailNotification(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestEmailNotification'](arg1, arg2, arg3, arg4, arg5);
}

export function TestOllamaConnection(arg1) {
  return window['go']['main']['App']['TestOllamaConnection'](arg1);
}

export function TestProxyConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestProxyConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function TestTelegramNotification(arg1, arg2) {
  return window['go']['main']['App']['TestTelegramNotification'](arg1, arg2);
}

export function ToggleScheduledTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleScheduledTask'](arg1, arg2);
}

export function Traceroute(arg1) {
  return window['go']['main']['App']['Traceroute'](arg1);
}

export function UpdateProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3, arg4, arg5);
}

export function VacuumDatabase() {
  return window['go']['main']['App']['VacuumDatabase']();
}

export function ValidateTOTPCode(arg1, arg2) {
  return window['go']['main']['App']['ValidateTOTPCode'](arg1, arg2);
}
