// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {files} from '../models';
import {auth} from '../models';
import {domain} from '../models';
import {identity} from '../models';
import {threat} from '../models';
import {projects} from '../models';
import {db} from '../models';
import {network} from '../models';
import {scheduler} from '../models';
import {ai} from '../models';
import {scanner} from '../models';

export function AddScheduledTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function AddWatchTarget(arg1:string,arg2:string):Promise<void>;

export function AnalyzeDocument(arg1:string):Promise<files.DocumentAnalysisResult>;

export function AnalyzePassword(arg1:string):Promise<auth.PasswordAnalysisResult>;

export function AnalyzePhishing(arg1:string):Promise<domain.PhishingResult>;

export function AnalyzeWithAI(arg1:string,arg2:string):Promise<string>;

export function BookmarkLog(arg1:number,arg2:boolean):Promise<void>;

export function CheckEmailBreach(arg1:string):Promise<identity.EmailBreachResult>;

export function CheckForUpdate():Promise<boolean>;

export function CheckIPReputation(arg1:string):Promise<threat.IPReputationResult>;

export function CheckPasswordBreach(arg1:string):Promise<number>;

export function CheckPastes(arg1:string):Promise<threat.PasteMonitorResult>;

export function CompareHashes(arg1:string,arg2:string):Promise<files.CompareResult>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<projects.Project>;

export function DecodeQR(arg1:string):Promise<files.QRResult>;

export function DeleteAllQueryLogs():Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteQueryLogs(arg1:Array<number>):Promise<void>;

export function EncodeAll(arg1:string):Promise<Record<string, string>>;

export function ExportShadowScanPDF(arg1:domain.ShadowScanResult):Promise<Array<number>>;

export function ExtractFileMetadata(arg1:string):Promise<files.MetadataResult>;

export function ExtractImageEXIF(arg1:string):Promise<files.EXIFResult>;

export function FingerprintWeb(arg1:string):Promise<domain.FingerprintResult>;

export function GenerateDorks(arg1:string):Promise<Array<domain.DorkCategory>>;

export function GenerateIdentityDorks(arg1:string):Promise<identity.DorkResult>;

export function GeneratePasswords(arg1:auth.GeneratorOptions):Promise<Array<auth.GeneratedPassword>>;

export function GenerateTOTPSecret(arg1:string,arg2:string):Promise<auth.TOTPSecret>;

export function GenerateWeeklyReport():Promise<string>;

export function GetAIHistory(arg1:number):Promise<Array<Record<string, string>>>;

export function GetAIProvider():Promise<string>;

export function GetBadges():Promise<Array<db.Badge>>;

export function GetClipboardWatcherEnabled():Promise<boolean>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetHTTPHeaders(arg1:string):Promise<domain.URLScanResult>;

export function GetLicense():Promise<string>;

export function GetMyIP():Promise<network.MyIPResult>;

export function GetOllamaStatus():Promise<boolean>;

export function GetProjects():Promise<Array<projects.Project>>;

export function GetQueryHistory(arg1:string,arg2:number):Promise<Array<db.QueryHistory>>;

export function GetQueryLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<Record<string, any>>;

export function GetRecentActivity(arg1:number):Promise<Array<Record<string, string>>>;

export function GetScheduledTasks():Promise<Array<scheduler.ScheduledTask>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetTOTPCode(arg1:string):Promise<auth.TOTPCode>;

export function GetThreatFeedData():Promise<threat.ThreatFeedResult>;

export function GetVersion():Promise<string>;

export function GetWatchTargets():Promise<Array<threat.WatchTarget>>;

export function HashFilePath(arg1:string):Promise<files.HashSet>;

export function HashFileVT(arg1:string):Promise<files.HashLookupResult>;

export function HashText(arg1:string):Promise<files.HashSet>;

export function InspectSSL(arg1:string):Promise<domain.SSLResult>;

export function ListOllamaModels():Promise<Array<ai.OllamaModelInfo>>;

export function LookupBGP(arg1:string):Promise<network.BGPResult>;

export function LookupDNS(arg1:string):Promise<domain.DNSResult>;

export function LookupDNSForward(arg1:string):Promise<network.DNSLookupResult>;

export function LookupDNSReverse(arg1:string):Promise<network.ReverseDNSResult>;

export function LookupGeoMap(arg1:Array<string>):Promise<network.GeoMapResult>;

export function LookupHashVT(arg1:string):Promise<files.HashLookupResult>;

export function LookupIPIntel(arg1:string):Promise<network.IPIntelResult>;

export function LookupPhone(arg1:string):Promise<identity.PhoneLookupResult>;

export function LookupWHOIS(arg1:string):Promise<domain.WHOISResult>;

export function LookupWayback(arg1:string):Promise<identity.WaybackResult>;

export function MonitorPastes(arg1:string):Promise<auth.PasteMonitorResult>;

export function OpenAnyFileDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenImageDialog(arg1:string):Promise<string>;

export function ParseEmailHeader(arg1:string):Promise<auth.EmailHeaderResult>;

export function PingHost(arg1:string,arg2:number):Promise<network.PingResult>;

export function ProcessEncoder(arg1:string,arg2:string,arg3:string,arg4:number):Promise<auth.EncoderResult>;

export function QueryAI(arg1:string):Promise<string>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function RemoveScheduledTask(arg1:number):Promise<void>;

export function RemoveWatchTarget(arg1:string):Promise<void>;

export function RunOSINTDashboard(arg1:string):Promise<identity.OSINTDashboardResult>;

export function RunSelfScan():Promise<scanner.SelfScanResult>;

export function RunShadowScan(arg1:domain.ScanConfig):Promise<domain.ShadowScanResult>;

export function SaveAIMessage(arg1:string,arg2:string):Promise<void>;

export function SaveQueryLog(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function ScanPorts(arg1:string,arg2:string):Promise<network.PortScanResult>;

export function ScanURL(arg1:string):Promise<domain.URLScanResult>;

export function SearchCVE(arg1:string):Promise<threat.CVESearchResult>;

export function SearchUsername(arg1:string):Promise<identity.UsernameSearchResult>;

export function SetAIProvider(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetClipboardWatcherEnabled(arg1:boolean):Promise<void>;

export function TestAIProvider(arg1:string,arg2:string,arg3:string):Promise<ai.ProviderStatus>;

export function TestEmailNotification(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function TestOllamaConnection(arg1:string):Promise<boolean>;

export function TestProxyConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function TestTelegramNotification(arg1:string,arg2:string):Promise<void>;

export function ToggleScheduledTask(arg1:number,arg2:boolean):Promise<boolean>;

export function Traceroute(arg1:string):Promise<network.TracerouteResult>;

export function UpdateProject(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function VacuumDatabase():Promise<void>;

export function ValidateTOTPCode(arg1:string,arg2:string):Promise<boolean>;
